# Generated by Django 6.0.1 on 2026-02-01 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinguisticArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Área Lingüística')),
                ('description', models.TextField(blank=True, verbose_name='Descripción del Área')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del Ejercicio')),
                ('instructions', models.TextField(verbose_name='Instrucciones de Creación')),
                ('example_text', models.TextField(blank=True, verbose_name='Ejemplo Guía')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='linguistics.linguisticarea')),
            ],
        ),
    ]
