# Generated by Django 6.0.2 on 2026-02-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
        ("linguistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="lessons.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="linguistics.linguisticarea",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="level",
            field=models.CharField(
                choices=[
                    ("Básico", "Básico"),
                    ("Intermedio", "Intermedio"),
                    ("Avanzado", "Avanzado"),
                ],
                default="Básico",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="linguisticarea",
            name="description",
            field=models.TextField(),
        ),
    ]
