# Generated by Django 6.0.1 on 2026-02-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='example_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='linguisticarea',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
