# Generated by Django 6.0.2 on 2026-02-06 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
        ("linguistics", "0002_exercise_lesson_alter_exercise_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="correct_answer",
            field=models.TextField(default="", help_text="La respuesta esperada"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exercise",
            name="feedback",
            field=models.TextField(default="", help_text="Explicación pedagógica"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exercise",
            name="lesson",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="lessons.lesson",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="level",
            field=models.CharField(default="Básico", max_length=50),
        ),
    ]
