# Generated by Django 6.0.1 on 2026-01-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('teacher', 'Profesor'), ('student', 'Estudiante')], default='student', max_length=10),
        ),
    ]
