# Generated by Django 6.0.1 on 2026-02-01 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linguistics', '0002_alter_exercise_example_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Respuesta del Alumno')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='Retroalimentación')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Revisado')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='linguistics.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
            },
        ),
    ]
